version: '3.1'

networks: 
  default:

volumes: 
  mysql_data:
    driver: local

services: 
  mysql:
    image: mysql:8.0.26
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes: 
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  api:
    image: bienemann/challenge:latest
    build: 
      dockerfile: ./Dockerfile-multistage
      context: ./
    ports: 
      - "8080:8080"
    environment: 
      - MYSQL_HOST
      - MYSQL_PASSWORD
    depends_on:
       mysql:
         condition: service_healthy
